# Generated by Django 4.1.3 on 2023-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان اعتبار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قیمت')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضحیات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name=' توضیحات اصلی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / حذف نشده')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
