# Generated by Django 4.1.3 on 2023-05-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='count',
        ),
    ]
