# Generated by Django 4.1.3 on 2023-02-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0004_remove_business_customer'),
        ('customer_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscustomer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Businesses.business'),
        ),
    ]
