# Generated by Django 4.1.3 on 2023-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_businessowner_company'),
        ('customer_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscustomer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='login_signup.businessowner'),
        ),
    ]
