# Generated by Django 4.1.3 on 2023-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'کسب و کار',
                'verbose_name_plural': 'کسب و کارها',
            },
        ),
    ]
