# Generated by Django 4.1.3 on 2023-02-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_signup', '0001_initial'),
        ('Businesses', '0001_initial'),
        ('customer_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='login_signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_business', to='login_signup.businessowner'),
        ),
        migrations.AddField(
            model_name='business',
            name='customer',
            field=models.ManyToManyField(related_name='business', to='customer_login.businesscustomer'),
        ),
    ]
