# Generated by Django 4.1.3 on 2023-04-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_signup', '0001_initial'),
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_business', to='login_signup.businessowner'),
        ),
    ]
