# Generated by Django 4.1.3 on 2023-05-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_owner',
        ),
    ]
