# Generated by Django 4.1.3 on 2023-02-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='login_signup',
            new_name='business_owner',
        ),
    ]
