# Generated by Django 4.1.3 on 2023-02-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0003_rename_login_signup_business_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='customer',
        ),
    ]
