# Generated by Django 4.1.3 on 2023-02-28 12:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('siteuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_active_code', models.CharField(editable=False, max_length=100, verbose_name='کد فعال سازی ایمیل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر آواتار')),
            ],
            options={
                'verbose_name': 'صاحب کسب وکار',
                'verbose_name_plural': 'صاحبان کسب و کار',
            },
            bases=('users.siteuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
