# Generated by Django 4.1.3 on 2023-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کسب و کار'),
        ),
    ]
